# Generated by Django 5.1.6 on 2025-03-02 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('brend', models.CharField(max_length=200)),
                ('narx1', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('narx2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('olchov', models.CharField(max_length=10)),
                ('oxirgi_sana', models.DateTimeField(blank=True, null=True)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('dokon', models.CharField(max_length=200)),
                ('manzil', models.CharField(max_length=200)),
                ('qarz', models.FloatField()),
                ('tel', models.CharField(max_length=10)),
                ('bolim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bolim')),
            ],
        ),
    ]
